name: Docker multiarch publish
# from https://github.com/marklagendijk/node-toogoodtogo-watcher/blob/master/.github/workflows/docker-multiarch-publish.yml

on:
  push:
    branches: [ master, staging ]
    paths:
      - '*'
      - '!README.md'
      - '!changelog.md'
      - '!\.gitignore'
      - '!\.github/workflows/*'
  workflow_dispatch: # Manual trigger

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine tag
        id: determine-tag
        run: |
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            echo "::set-output name=DOCKER_TAG::latest"
          else
            echo "::set-output name=DOCKER_TAG::$(echo $GITHUB_REF | cut -d/ -f3)"
          fi
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.determine-tag.outputs.DOCKER_TAG }}