name: Release
on:
  push:
    branches:
      - master
    paths:
      - 'changelog.md'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Changelog
      id: get_changelog
      run: |
        VERSION=$(sed -n 's/## \([0-9.]*\).*/\1/p' changelog.md | head -n 1)
        echo "::set-output name=version::$VERSION"
        CHANGELOG=$(awk '/## '$VERSION'/{flag=1;next}/##/{flag=0}flag' changelog.md)
        printf "## %s (date)\n\n%s" $VERSION "$CHANGELOG"
        echo "::set-output name=changelog::$CHANGELOG"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        tag_name: ${{ steps.get_changelog.outputs.version }}
        release_name: Release ${{ steps.get_changelog.outputs.version }}
        body: ${{ steps.get_changelog.outputs.changelog }}
        draft: false
        prerelease: false
